sudo: false

language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

env:
  - TRAVIS_NODE_VERSION="stable"
  - TRAVIS_NODE_VERSION=5
  - TRAVIS_NODE_VERSION=4
  - TRAVIS_NODE_VERSION=0.12

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install: "npm install"

script: "./node_modules/.bin/mocha test/downloaded-files-rights.js"
